### ISSUE TITLE
FLAG seemingly not being honoured

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#26]
Using the command from #23, I eventually get this plot:

![image](https://user-images.githubusercontent.com/6470079/56823787-23953280-6855-11e9-9f53-08e830127d79.png)

Those extremely high amplitudes are from RFI, but this is all flagged in the MS:

```
In [1]: from pyrap.tables import table
In [2]: tab=table("scratch/Tarantula_LO_4ch8s.ms")
Successful readonly open of default-locked table scratch/Tarantula_LO_4ch8s.ms: 41 columns, 5715090 rows
In [3]: a=tab.getcol("SC_PEEL_HR_DATA"); fl=tab.getcol("FLAG")
In [4]: a[~fl].max()In [4]: a[~fl].max()
Out[4]: (61.56482+20.043154j)
In [5]: a.max()
Out[5]: (39597.668+10495.803j)
```

Flagged values should not be showing up in the plot.

**Comment by Mulan-94** [comment]
I think this is fixed now, do check
