### ISSUE TITLE
Plot both correlations for gain tables

### ISSUE THREAD

**Issue by Mulan-94** [ratt-ru/ragavi#27]
Make them switchable on the plot.

**Comment by Mulan-94** [comment]
ping @KshitijT

**Comment by KshitijT** [comment]
This is done and in the current version, @Mulan-94 ?

**Comment by Mulan-94** [comment]
Unfortunately not yet @KshitijT

**Comment by o-smirnov** [comment]
So are both correlations plotted with the same symbol at the moment, or just the first one is plotted?

**Comment by Mulan-94** [comment]
@o-smirnov yes both are plotted with the same symbols

**Comment by IanHeywood** [comment]
What I cannot get to work with the HTML interface is plotting a single correlation for a single antenna. Selecting a single antenna seems to load both correlations by default (irrespective of the correlation selection checkboxes), and adjusting the checkboxes deselects the antenna.

**Comment by Mulan-94** [comment]
Hi @IanHeywood, If I understand the issue correctly, I think a possible work-around for this is deselecting all the antennas first, then selecting the correlation you want and then selecting that antenna from the legends.

**Comment by IanHeywood** [comment]
@Mulan-94 that works, thanks!
