### ISSUE TITLE
Denote different fields with different markers

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/ragavi#28]
Currently Ragavi produces **per field** plots for gaintables having multiple fields.In cases like the gain calibration and fluxscale gain tables, it is much better to have multiple fields in the same plot to examine if  the calibration process has gone through. 
Can we add this capability to the Ragavi?

**Comment by Mulan-94** [comment]
@KshitijT this feature is ready now, but the scatters will have a line thickness of colour black depending on the field id. i.e. scatters for field 0 will not have any lines, field 1 with thickness 1 and so on. Is this acceptable?

**Comment by KshitijT** [comment]
@Mulan-94 , could you please post a plot?

**Comment by Mulan-94** [comment]
![image](https://user-images.githubusercontent.com/12611059/60656693-2feacc80-9e50-11e9-8958-6ea0c7795a4f.png)

**Comment by KshitijT** [comment]
Awesome ! If it is not going to be too much to add, could we also have field selectors ?

**Comment by o-smirnov** [comment]
How about different symbols (circles, squares, triangles, etc.) for different fields?
