### ISSUE TITLE
optionally plot flagged data using different symbol (or color)

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#30]
Getting a plot like this in the MeerKATHI output:

![image](https://user-images.githubusercontent.com/6470079/60589172-218da980-9d99-11e9-908a-e9a0c5aefc2f.png)

However, chunks of the band are definitely flagged, so we would expect to see corresponding gaps in the bandpass plot. @Mulan-94 could you please check if you're plotting flagged data here?

**Comment by o-smirnov** [comment]
Ah hang on there are no flags in the table it seems...

**Comment by Mulan-94** [comment]
ok @o-smirnov . Just a hint also, you can switch off all the legends to get a slightly bigger plot by clicking on the showing legends drop down menu and selecting none.

**Comment by o-smirnov** [comment]
Yeah our bad. I don't think they're properly flagged in this case.

In any case, I have a feature request: can we plot flagged data (in a different colour), and have a checkbox for whether to plot it or not?

**Comment by o-smirnov** [comment]
OK, the error was elsewhere (see https://github.com/ska-sa/meerkathi/issues/523), but since this has turned into a feature request, I'm renaming the issue and leaving it open.

Flagged data needs to look different. Since colour is already reserved for antennas, and given the request in #28, one idea would be:

* different shapes for different fields (circles, squares, triangles)

* black outline (width=1) for flagged data, no outline for unflagged data?

* have a selector to show flagged data. Off by default.
