### ISSUE TITLE
Rearrange selector panel, legend and tweak font sizes

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#31]
The plotter is awesome, but I can't help feeling we could use the real estate better. This is what it looks like on a low-res screen:

![image](https://user-images.githubusercontent.com/6470079/60652243-28272a00-9e48-11e9-8065-989d6e544029.png)

This is what it looks like on a hi-res screen:
![image](https://user-images.githubusercontent.com/6470079/60651477-94089300-9e46-11e9-884c-cb504f156c0d.png)

There is a lot of unutilized screen space, while the business end (the plots themselves) are cramped. Suggestions:

* any way to display the antenna legend under the plot rather than to the right of it?

* smaller fonts for legend, and definitely for the plot title

* can the selector elements on the left be arranged in a row along the top of the screen instead?

**Comment by Mulan-94** [comment]
@o-smirnov yes that can be done, but also, you could hide the legends altogether by clicking on that **showing legends** dropdown and selecting `none`, for now. I will decrease the font sizes and move the selectors.

**Comment by o-smirnov** [comment]
OK looking much better. Suggested fixes:

* add field marker to field label (so that we can tell which field is which). Lookup HTML entitites for appropriate Unicode characters (circles, diamonds, etc.) and add them to the text of the field selectors

* Plot title -- smaller font 

* "Time [s]" to "Time bin" (in axis labels and in titles)

* Lay controls across (side by side, rather than stacked, as much as you can)

* Make controls more narrow (half the width of the current glyph size and alpha selectors, and also reduce the width of the "Deselect all antennas" etc. buttons)

* Move "median amplitude X" and "median phase Y" labels to inside the plot titles (e.g. "Amplitude vs Time bin (median: X)"

**Comment by Mulan-94** [comment]
Sample output incorporating suggested changes:
![image](https://user-images.githubusercontent.com/12611059/61002122-32be5380-a361-11e9-9e54-293fcd1a8f71.png)

- Plots will scale automatically

**Comment by o-smirnov** [comment]
Oh yes, really looking slick!

Is it just me, or do the two field labels next to the checkboxes have slightly different font sizes?

**Comment by Mulan-94** [comment]
Same size, it's the markup symbol causing the illusion. Fixing it

**Comment by o-smirnov** [comment]
Also, typo in the "Glyph alpha" label.

**Comment by SpheMakh** [comment]
Great! Can we make a new release with these changes
