### ISSUE TITLE
Add glyph alpha selector

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#32]
I'm finding the current symbols a little big for the 64-antenna case:

![image](https://user-images.githubusercontent.com/6470079/60672039-bdd8ae80-9e74-11e9-9500-217b7d8e98a5.png)

The blue end is completely covered by the red end. Perhaps it would help if the symbols were smaller and/or more transparent.

Optimal settings may depend on the number of antennas plotted. And it's hard to know without trying. Would it be difficult to add a selector for symbol size, and a selector for transparency? Then once we've played with them for a bit, maybe later we can reduce it to some small number of sensible defaults.

**Comment by Mulan-94** [comment]
There is already a size selector currently, I will do one for transparency as well.

**Comment by o-smirnov** [comment]
There is a size selector already? Help, I'm too old and blind to find it...
