### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/ragavi#35]
I get this error when running ragavi 0.0.7 on python 2.7 

```
12.07.2019@15:57:56 - ragavi.vis_utils - ERROR - Oops ... !
Traceback (most recent call last):
  File "/usr/local/bin/ragavi", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 1466, in main
    stats_text = stats_display(mytab, gain_type, doplot, corr, field)
  File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 1213, in stats_display
    u"\u00b0")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 0: ordinal not in range(128)


```

**Comment by Mulan-94** [comment]
This could be is because of utf-8  specific characters in `ragavi` (for the field symbols).
Testing it from my end.

**Comment by o-smirnov** [comment]
Funny how I've never heard of this problem before last week, and now everyone's getting it, like a bad case of rash. I guess it's here:
```
text2 = "Field {} Median: {:.4f}{}".format(field, med_y2,
                                                   u"\u00b0")
```
I think the "{}" conversion is trying to convert your unicode string into an ``str``, which invokes ``unicode.encode("ascii")`` under the hood. Try ``u"\u00b0".encode("utf-8")``?

**Comment by Mulan-94** [comment]
Oh yeah. Fixed it now. I do note however, that if `encode` is invoked for `python3` one ends up with hex characters on a string.

**Comment by SpheMakh** [comment]
The fix works. Can we make another release
