### ISSUE TITLE
Plot delays as a function of time

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#45]
For K solutions, since we often solve for K over time, it would be useful to have a plot where X is the time axis (i.e. exactly as is done for G now).

**Comment by Mulan-94** [comment]
@o-smirnov Noted. Will be in the next release

**Comment by o-smirnov** [comment]
Cool! 

But wait, we still want the old behaviour too (delay-versus-antenna....) Both types of plots. Can we make this selectable? (Command line or GUI?)

**Comment by Mulan-94** [comment]
It can be easily made possible over the command line... Maybe a bit tricky over GUI but I can still try

**Comment by Mulan-94** [comment]
Implemented on command line under #48 . Use the argument `-kx` of `--k-xaxis` to select antenna or time. Default will be antenna
