### ISSUE TITLE
Incorrect time axis in plot containing multiple fields

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#46]
I'm seeing something like this:

![image](https://user-images.githubusercontent.com/6470079/69538943-1c213d80-0f8c-11ea-8e1e-0a595c63e9d1.png)

This is incorrect, because I know that the first scan of field 2 (the squiggly lines) was actually midway through the observation and not at the start. So it just looks to me like all the scans of field 2 were shifted left, to make its starting time 0.

I think you're simply computing ``time-min(time)`` on a per-field basis, when in fact min(time) should be just one number for the entire table.

**Comment by Mulan-94** [comment]
Yes you are right. Thanks for pointing this out. It will be fixed
