### ISSUE TITLE
Unable to plot multiple DDIDs (SPWs)

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/ragavi#49]
The help says:

```
--ddid                SPECTRAL_WINDOW_ID or ddid number. Defaults to all
```

but the default behaviour only plots SPW 0.

The `--ddid` switch also only seems to accept a single integer, so I cannot figure out how to plot multiple SPWs on a single plot.

**Comment by IanHeywood** [comment]
Sorry, this `ragavi-gains` by the way.

**Comment by Mulan-94** [comment]
@IanHeywood Thanks for this report, I am having a look
