### ISSUE TITLE
ragavi-gains (intermittently) hangs on bandpass plot with dask-ms==0.2.4

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#64]
Seems to work fine with 0.2.3!

This will hang it reliably: 

```
while true; do ragavi-gains --table mypipelinerun-1524929477-1gc1_primary_cal.B0 --gaintype B --cmap coolwarm --doplot ap --field 2 --htmlname B0 --k-xaxis time; done
```

Table attached.

[b0.zip](https://github.com/ratt-ru/ragavi/files/4606571/b0.zip)

**Comment by sjperkins** [comment]
@o-smirnov @Mulan-94 https://github.com/ska-sa/dask-ms/pull/113 fixes this.

I'd like to spend time on a more comprehensive solution, but given that you're trying to release CARAcal, would a quick merge and release be satisfactory?

**Comment by Mulan-94** [comment]
Sorry @sjperkins I missed your comment on that issue last week. I will test the branch out today

**Comment by o-smirnov** [comment]
Thanks! No, we can test an image with the branch for now, can even release
with it if push comes to shove. But let us test first.

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by sjperkins** [comment]
I'm testing with it on my side and it seems to run through. Thanks for the table and the test case, they're good reproducers.

**Comment by o-smirnov** [comment]
> Sorry @sjperkins I missed your comment on that issue last week. I will test the branch out today

So did I. There's a lesson for us in here somewhere @Mulan-94...

Let me stress test this branch.

**Comment by Mulan-94** [comment]
@sjperkins this seems to do it for `ragavi-gains`. I've run it like 50 times with @o-smirnov 's problematic table, as well as other tables, and it goes through fine. Thank you.
