### ISSUE TITLE
ragavi-vis intermittently hangs with dask-ms==0.2.4

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#65]
Flagging it up for now, to be debugged later. Kern-dev will become kern-6 soon enough, and then we have a real problem! Possibly related to #64, but who knows really...

**Comment by o-smirnov** [comment]
P.S. The obvious suspects are the new casacore-dev/python-casacore versions in kern-dev. Going back to kern-5 and a pip install of python-casacore==3.3.0 eliminates the hang.

**Comment by o-smirnov** [comment]
OK, nevermind, I got it to hang with kern-5 as well. The new symptom is a 0% progress bar that prints itself endlessly.

Going back to dask-ms==0.2.3 seems to have solved the problem. So definitely looks related to #64, and definitely need @sjperkins's eye.

**Comment by sjperkins** [comment]
Does dask-ms 0.2.5 resolve this issue?

**Comment by o-smirnov** [comment]
Yes!
