### ISSUE TITLE
ragavi-gains: htmlname seemingly ignored

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#69]
Invoked like this:
```
$ ragavi-gains --table caltables/od1-1557766852_sdp_l0_1284.full_pol-1gc1_secondary.F0 --gaintype F  --cmap coolwarm --doplot ap --field 0,1,2 --htmlname diagnostic_plots/crosscal/od1-1557766852_sdp_l0_1284.full_pol-1gc1_secondary.F0_ap1.html --k-xaxis time
...
08.06.2020@21:31:25 - ragavi       - INFO       - Rendered HTML: /home/oms/projects/OldDevils/output-od1/od1-1557766852_sdp_l0_1284.full_pol-1gc1_secondary.F0_ap.html
$
```

Note that this was not the filename I was looking for...

**Comment by IanHeywood** [comment]
I just came along to report this issue, having moved from using the version in:

```
/idia/software/containers/STIMELA_IMAGES/stimela_ragavi_1.5.0.sif
```

to:

```
/software/astro/caracal/STIMELA_IMAGES_1.6.5/stimela_ragavi_1.7.0.sif
```

Perhaps this fix hasn't made it to the containerised version yet?

**Comment by KshitijT** [comment]
Also, those images haven't been updated yet.

**Comment by Mulan-94** [comment]
Hi @IanHeywood, please try version `1.7.2`

**Comment by IanHeywood** [comment]
Thanks both. It's mostly being used for scripted data reduction on IDIA / CHPC so I'll just wait until the fix makes its way to the stimela container. Cheers.
