### ISSUE TITLE
ragavi-gains: nothing plotted for Dref tables

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#80]
Trying to look at a Dref table produced by Francesca's worker, I just get a blank plot like so:

![image](https://user-images.githubusercontent.com/6470079/95852366-ee83e500-0d53-11eb-94b8-04411fe1cebd.png)

The table is not empty though:

![image](https://user-images.githubusercontent.com/6470079/95852469-183d0c00-0d54-11eb-8ead-dfbecdccfe6b.png)

Maybe there's confusion between this one and Df? The Dref table has no frequency axis (but may have one or more points in time per each antenna... so it's more like a K table...), while Df is bandpass-like.

**Comment by Mulan-94** [comment]
Sorry about this, let me have a look. Do you possibly have this table?

**Comment by o-smirnov** [comment]
See e.g. ``/net/simon/home/oms/projects/polcal/output-fleak/caltables/fl-MS-2pcal.Dref``

**Comment by Mulan-94** [comment]
Here's the output with the x-axis as time:
![image](https://user-images.githubusercontent.com/12611059/96111184-279d9000-0ee1-11eb-9d39-0d170d05224d.png)

Shall I change the default x-axis for Dref tables to time then?

**Comment by o-smirnov** [comment]
Yes, perfect!
